services:
  postgres:
    image: postgres:latest
    restart: no
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./tmp/db/:/var/lib/postgresql/data
    # command: "-c logging_collector=on -c log_statement=all"
